# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y gcc libpq-dev build-essential && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy the project files
COPY pyproject.toml ./
COPY LICENSE ./
COPY README.md ./
COPY src ./src
COPY uv.lock ./

# Install pip and build tools
RUN pip install --upgrade pip

# Install the package in production mode
RUN pip install . --no-cache-dir

# Expose port if needed (not strictly required for stdio server)

# Command to run the MCP server
CMD ["mcp-telegram", "start"]
